name: test2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3  # Added http package dependency
  cupertino_icons: ^1.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.0  # Added flutter_native_splash package
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/pokemon.jpg
